-- ============================================================
-- BMC Website — Supabase Schema
-- Run this in: Supabase Dashboard → SQL Editor → New query
-- ============================================================


-- ── 0. difficulty_levels ────────────────────────────────────
-- Lookup table: integer id → display label + default points

CREATE TABLE IF NOT EXISTS difficulty_levels (
  id     INT  PRIMARY KEY,
  label  TEXT NOT NULL,
  points INT  NOT NULL DEFAULT 3
);

ALTER TABLE difficulty_levels ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read difficulty_levels"
  ON difficulty_levels FOR SELECT
  USING (true);

INSERT INTO difficulty_levels (id, label, points) VALUES
  (1, 'Easy',   3),
  (2, 'Medium', 5),
  (3, 'Hard',   8)
ON CONFLICT (id) DO NOTHING;


-- ── 1. problems ─────────────────────────────────────────────
-- Each row represents one difficulty tier of one cycle.
-- cycle_number groups the three tiers together.

-- Each row is a 大題 (parent_id NULL) or one 步驟 of it (parent_id set).
-- cycle_number groups the main problem + its steps together.
-- points: custom per-step score; NULL falls back to difficulty_levels.points.
CREATE TABLE IF NOT EXISTS problems (
  id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cycle_number         INT          NOT NULL,
  difficulty_level_id  INT          REFERENCES difficulty_levels(id),  -- NULL for 大題
  points               INT,                                             -- 自訂分數，NULL = 用 difficulty_levels
  title                TEXT         NOT NULL,
  latex                TEXT         NOT NULL,
  solution             TEXT,
  start_date           TIMESTAMPTZ,
  end_date             TIMESTAMPTZ,
  is_active            BOOLEAN      NOT NULL DEFAULT false,
  created_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

ALTER TABLE problems ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read problems"
  ON problems FOR SELECT
  USING (true);

-- Insert seed data for Cycle 1
INSERT INTO problems (cycle_number, difficulty_level_id, title, latex, is_active)
VALUES
  (1, 1, '等差數列求和',
   '計算 $1 + 2 + 3 + \cdots + 100$ 的和。',
   true),
  (1, 2, '證明 √2 為無理數',
   '證明$\sqrt{2}$是無理數。',
   true),
  (1, 3, '立方和公式',
   '對於任意正整數 $n$，證明：$\sum_{k=1}^{n} k^3 = \left( \frac{n(n+1)}{2} \right)^2$',
   true);


-- ── 2. submissions ──────────────────────────────────────────

CREATE TABLE IF NOT EXISTS submissions (
  id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  problem_id     BIGINT       NOT NULL REFERENCES problems(id) ON DELETE RESTRICT,
  student_name   TEXT,                     -- NULL 時表示匿名提交（配合 is_anonymous）
  is_anonymous   BOOLEAN      NOT NULL DEFAULT false,
  answer         TEXT         NOT NULL,
  is_correct     BOOLEAN,
  score          INT          NOT NULL DEFAULT 0,
  submitted_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

ALTER TABLE submissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public insert submissions"
  ON submissions FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Public read submissions"
  ON submissions FOR SELECT
  USING (true);

-- Admin review policies (Day 6): allow marking submissions correct/incorrect.
-- In a real deployment this should be restricted to authenticated admin roles;
-- for the BMC school-club context public update is the pragmatic v1 choice.
CREATE POLICY "Public update submissions"
  ON submissions FOR UPDATE
  USING (true);

-- Admin insert/update problems (Day 6)
CREATE POLICY "Public insert problems"
  ON problems FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Public update problems"
  ON problems FOR UPDATE
  USING (true);


-- ── 3. speed_records ────────────────────────────────────────

CREATE TABLE IF NOT EXISTS speed_records (
  id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_name   TEXT         NOT NULL,
  score          INT          NOT NULL,
  correct_count  INT          NOT NULL DEFAULT 0,
  total_count    INT          NOT NULL DEFAULT 0,
  time_seconds   INT          NOT NULL,
  mode           TEXT         NOT NULL DEFAULT 'solo',
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

ALTER TABLE speed_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public insert speed_records"
  ON speed_records FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Public read speed_records"
  ON speed_records FOR SELECT
  USING (true);


-- ============================================================
-- Migration for existing databases
-- ============================================================
-- If you already have the old schema (problems.level TEXT, problems.label TEXT),
-- run this section SEPARATELY (not together with the CREATE TABLE above):

/*
-- Step 1: create the lookup table
CREATE TABLE difficulty_levels (
  id     INT  PRIMARY KEY,
  label  TEXT NOT NULL,
  points INT  NOT NULL DEFAULT 3
);

ALTER TABLE difficulty_levels ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read difficulty_levels"
  ON difficulty_levels FOR SELECT
  USING (true);

INSERT INTO difficulty_levels (id, label, points) VALUES
  (1, 'Easy',   3),
  (2, 'Medium', 5),
  (3, 'Hard',   8);

-- Step 2: add the new FK column (nullable first)
ALTER TABLE problems ADD COLUMN difficulty_level_id INT;

-- Step 3: map old TEXT values to new INT ids
UPDATE problems SET difficulty_level_id = CASE level
  WHEN 'easy'   THEN 1
  WHEN 'medium' THEN 2
  WHEN 'hard'   THEN 3
END;

-- Step 4: make NOT NULL + add FK
ALTER TABLE problems ALTER COLUMN difficulty_level_id SET NOT NULL;
ALTER TABLE problems ADD CONSTRAINT problems_level_fk
  FOREIGN KEY (difficulty_level_id) REFERENCES difficulty_levels(id);

-- Step 5: drop old columns
ALTER TABLE problems DROP COLUMN level;
ALTER TABLE problems DROP COLUMN label;
*/


-- ============================================================
-- Migration: add solution column
-- ============================================================
-- Run this to add the official-solution field to an existing DB:

/*
ALTER TABLE problems ADD COLUMN IF NOT EXISTS solution TEXT;

-- Example: fill in solution for 立方和公式 (cycle 1, hard)
UPDATE problems SET solution = '證明：令 $S = \sum_{k=1}^{n} k^3$。已知 $\sum_{k=1}^{n} k = \frac{n(n+1)}{2}$。

$$
\begin{align}
n^4 - (n-1)^4 &= 4n^3 - 6n^2 + 4n - 1 \\
(n-1)^4 - (n-2)^4 &= 4(n-1)^3 - 6(n-1)^2 + 4(n-1) - 1 \\
&\;\vdots \\
2^4 - 1^4 &= 4 \cdot 2^3 - 6 \cdot 2^2 + 4 \cdot 2 - 1 \\
1^4 - 0^4 &= 4 \cdot 1^3 - 6 \cdot 1^2 + 4 \cdot 1 - 1
\end{align}
$$

累加得 $n^4 = 4S - 6\sum k^2 + 4\sum k - n$，整理後即得 $S = \left(\frac{n(n+1)}{2}\right)^2$。'
WHERE title = '立方和公式';

-- Then mark it as past problem
UPDATE problems SET is_active = false WHERE title = '立方和公式';
*/


-- ============================================================
-- Migration: remove points column from problems
-- ============================================================
-- Points are now managed exclusively in difficulty_levels.
-- Run this to clean up an existing DB:

/*
ALTER TABLE problems DROP COLUMN IF EXISTS points;
*/


-- ============================================================
-- Migration: 大題 + 步驟結構（2026-08-10）
-- ============================================================
-- 每週由「一道大題」+「N 個步驟」組成，降低門檻提升參與率。
--   - 大題：parent_id = NULL, step_number = NULL, difficulty_level_id = NULL
--   - 步驟：parent_id = 大題 id, step_number = 1..N,
--           difficulty_level_id = step_number（1=Easy 3pts, 2=Medium 5pts, 3=Hard 8pts）
-- 舊數據（parent_id 為 NULL 嘅單題）會被前端當做「單一步驟嘅大題」處理，唔需要遷移。
-- 喺 Supabase SQL Editor 執行：

ALTER TABLE problems
  ADD COLUMN IF NOT EXISTS parent_id   BIGINT REFERENCES problems(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS step_number INT;

-- 大題本身冇難度
ALTER TABLE problems ALTER COLUMN difficulty_level_id DROP NOT NULL;

CREATE INDEX IF NOT EXISTS idx_problems_parent ON problems(parent_id);


-- ============================================================
-- Migration: custom per-step points（2026-08-11）
-- ============================================================
-- 出題者可以自訂每步分數；NULL 時 fallback 到 difficulty_levels.points。
-- 喺 Supabase SQL Editor 執行：
ALTER TABLE problems ADD COLUMN IF NOT EXISTS points INT;


-- ============================================================
-- Migration: Speed Arena 實時對戰（2026-08-11）
-- ============================================================
-- Kahoot-style real-time battle. 狀態機全部由 DB 驅動，
-- 透過 Supabase Realtime (postgres_changes) 廣播。
--   1. Host create room → players join with the 6-digit code
--   2. Host advances questions via question_data JSONB
--   3. Players insert answers; Host tallies scores
-- 喺 Supabase SQL Editor 執行：

CREATE TABLE IF NOT EXISTS speed_rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,                -- 6 位 join code
  status TEXT NOT NULL DEFAULT 'waiting',   -- waiting / playing / ended
  current_question INT NOT NULL DEFAULT 0,  -- 0 = 未開始
  question_data JSONB,                      -- { text, options, correct, timeLimit }
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS speed_players (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id BIGINT REFERENCES speed_rooms(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  score INT NOT NULL DEFAULT 0,
  joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS speed_answers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id BIGINT REFERENCES speed_rooms(id) ON DELETE CASCADE,
  player_id BIGINT REFERENCES speed_players(id) ON DELETE CASCADE,
  question_index INT NOT NULL,
  is_correct BOOLEAN NOT NULL,
  answered_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE speed_rooms   ENABLE ROW LEVEL SECURITY;
ALTER TABLE speed_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE speed_answers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read speed_rooms"   ON speed_rooms   FOR SELECT USING (true);
CREATE POLICY "Public insert speed_rooms" ON speed_rooms   FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update speed_rooms" ON speed_rooms   FOR UPDATE USING (true);
CREATE POLICY "Public read speed_players"   ON speed_players   FOR SELECT USING (true);
CREATE POLICY "Public insert speed_players" ON speed_players   FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update speed_players" ON speed_players   FOR UPDATE USING (true);
CREATE POLICY "Public read speed_answers"   ON speed_answers   FOR SELECT USING (true);
CREATE POLICY "Public insert speed_answers" ON speed_answers   FOR INSERT WITH CHECK (true);
-- Host 端 judge 時要 UPDATE is_correct；冇呢條 policy 會靜默阻擋
-- （judge 失敗 → review 由 DB 讀返全部當錯）
CREATE POLICY "Public update speed_answers" ON speed_answers   FOR UPDATE USING (true);

-- Realtime 廣播要開：Supabase Dashboard → Database → Replication
-- 將呢三張表加入 "supabase_realtime" publication：
ALTER PUBLICATION supabase_realtime ADD TABLE speed_rooms;
ALTER PUBLICATION supabase_realtime ADD TABLE speed_players;
ALTER PUBLICATION supabase_realtime ADD TABLE speed_answers;






-- ============================================================
-- Migration: Speed Arena 改用 Realtime Broadcast（2026-08-12）
-- ============================================================
-- postgres_changes 收唔到（Realtime WAL 層面問題），改用官方推薦嘅
-- Broadcast + database trigger 方案。用 public broadcast（private: false）
-- 因為網站冇登入系統（anon key 無法通過 private channel 授權）。
-- 已驗證 client-to-client broadcast 正常（PONG 測試）。
-- 喺 Supabase SQL Editor 執行：

CREATE OR REPLACE FUNCTION public.broadcast_speed_room_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  room_id_val bigint;
  payload jsonb;
BEGIN
  -- speed_rooms 自己就係 room（id），其他表先有 room_id 欄位
  IF TG_TABLE_NAME = 'speed_rooms' THEN
    room_id_val := COALESCE(NEW.id, OLD.id);
  ELSE
    room_id_val := COALESCE(NEW.room_id, OLD.room_id);
  END IF;
  payload := jsonb_build_object(
    'table', TG_TABLE_NAME,
    'operation', TG_OP,
    'row', CASE WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END
  );
  PERFORM realtime.send(payload, 'room-change', 'room:' || room_id_val || ':updates', false);
  RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE TRIGGER trg_speed_rooms_broadcast
AFTER INSERT OR UPDATE ON public.speed_rooms
FOR EACH ROW EXECUTE FUNCTION public.broadcast_speed_room_change();

CREATE TRIGGER trg_speed_players_broadcast
AFTER INSERT OR UPDATE ON public.speed_players
FOR EACH ROW EXECUTE FUNCTION public.broadcast_speed_room_change();

CREATE TRIGGER trg_speed_answers_broadcast
AFTER INSERT OR UPDATE ON public.speed_answers
FOR EACH ROW EXECUTE FUNCTION public.broadcast_speed_room_change();


-- ============================================================
-- Migration: 填空題模式（2026-08-12）
-- ============================================================
-- 由 4 選 1 改為自由輸入。正確答案唔可以喺 client（question_data
-- 只含 text + timeLimit），答案存喺 room.deck，由 Host 端判斷。
-- 喺 Supabase SQL Editor 執行：

ALTER TABLE speed_rooms ADD COLUMN IF NOT EXISTS deck JSONB;      -- 成個題目 deck（含答案）
ALTER TABLE speed_answers ADD COLUMN IF NOT EXISTS chosen_value INT;  -- 玩家輸入嘅數字
ALTER TABLE speed_answers ALTER COLUMN is_correct DROP NOT NULL;      -- 玩家提交時未知，Host 判斷後填

-- ============================================================
-- Migration: LaTeX 答案支援（2026-08-12）
-- ============================================================
-- 玩家答案由純數字擴展為純 LaTeX 字符串（例如 \frac{1}{2}），
-- 配合題庫導入嘅長題/分數題。舊數字數據會自動轉成 TEXT。
-- 喺 Supabase SQL Editor 執行：

ALTER TABLE speed_answers ALTER COLUMN chosen_value TYPE TEXT;

-- ============================================================
-- Migration: 題庫導入（2026-08-12）
-- ============================================================
-- Kahoot-style 預製題庫：出題者提前準備題目，開房時揀題庫。
-- questions JSONB 格式同 room.deck 一致：{ text, answer, timeLimit }，
-- answer 係 string（數字或 LaTeX，例如 "\\frac{1}{2}"），judge 用
-- answer-match.js 做數學等價判定。
-- 喺 Supabase SQL Editor 執行：

CREATE TABLE IF NOT EXISTS question_banks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  questions JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE question_banks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read question_banks"   ON question_banks FOR SELECT USING (true);
CREATE POLICY "Public insert question_banks" ON question_banks FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update question_banks" ON question_banks FOR UPDATE USING (true);
CREATE POLICY "Public delete question_banks" ON question_banks FOR DELETE USING (true);

-- 題庫級「要求最簡形式」開關（2026-08-13）：成個題庫統一設置，
-- 唔使每題獨立標記。simplest=true 時玩家答案必須係最簡形式
-- （√4 → 2、2/4 → 1/2、5^4 → 625、4^6 保留冪因為 ≥1000）。
ALTER TABLE question_banks ADD COLUMN IF NOT EXISTS simplest BOOLEAN NOT NULL DEFAULT FALSE;
