-- Migration unit 1: schema_changes
-- Transaction mode: transactional
-- Boundary reason: default

DROP EXTENSION pg_net;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE UPDATE ON SEQUENCES FROM anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE UPDATE ON SEQUENCES FROM authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE UPDATE ON SEQUENCES FROM service_role;

CREATE SEQUENCE public.speed_records_id_seq;

CREATE TABLE public.difficulty_levels (
  id     integer NOT NULL,
  label  text    NOT NULL,
  points integer DEFAULT 3 NOT NULL
);

ALTER TABLE public.difficulty_levels
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.difficulty_levels
  ADD CONSTRAINT difficulty_levels_pkey PRIMARY KEY (id);

GRANT INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.difficulty_levels TO anon;

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.difficulty_levels TO authenticated;

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.difficulty_levels TO service_role;

CREATE POLICY "Public read difficulty_levels" ON public.difficulty_levels
  FOR SELECT
  USING (true);

CREATE TABLE public.problems (
  id                  bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  cycle_number        integer                  NOT NULL,
  title               text                     NOT NULL,
  latex               text                     NOT NULL,
  start_date          timestamp with time zone,
  end_date            timestamp with time zone,
  is_active           boolean                  DEFAULT false NOT NULL,
  created_at          timestamp with time zone DEFAULT now() NOT NULL,
  difficulty_level_id integer,
  solution            text,
  parent_id           bigint,
  step_number         integer,
  points              integer
);

ALTER TABLE public.problems
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.problems
  ADD CONSTRAINT problems_level_fk FOREIGN KEY (difficulty_level_id) REFERENCES public.difficulty_levels(id);

ALTER TABLE public.problems
  ADD CONSTRAINT problems_pkey PRIMARY KEY (id);

ALTER TABLE public.problems
  ADD CONSTRAINT problems_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.problems(id) ON DELETE CASCADE;

GRANT INSERT, SELECT, UPDATE ON public.problems TO anon;

GRANT MAINTAIN ON public.problems TO authenticated;

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.problems TO service_role;

CREATE INDEX idx_problems_parent ON public.problems (parent_id);

CREATE POLICY "Public insert problems" ON public.problems
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Public read problems" ON public.problems
  FOR SELECT
  USING (true);

CREATE POLICY "Public update problems" ON public.problems
  FOR UPDATE
  USING (true);

CREATE TABLE public.speed_records (
  id            bigint                   DEFAULT nextval('public.speed_records_id_seq'::regclass) NOT NULL,
  student_name  text                     NOT NULL,
  score         integer                  NOT NULL,
  correct_count integer                  DEFAULT 0 NOT NULL,
  total_count   integer                  DEFAULT 0 NOT NULL,
  time_seconds  integer                  NOT NULL,
  mode          text                     DEFAULT 'solo'::text NOT NULL,
  created_at    timestamp with time zone DEFAULT now() NOT NULL
);

ALTER SEQUENCE public.speed_records_id_seq OWNED BY public.speed_records.id;

ALTER TABLE public.speed_records
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.speed_records
  ADD CONSTRAINT speed_records_pkey PRIMARY KEY (id);

GRANT MAINTAIN ON public.speed_records TO authenticated;

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.speed_records TO service_role;

CREATE POLICY "Public insert speed_records" ON public.speed_records
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Public read speed_records" ON public.speed_records
  FOR SELECT
  USING (true);

CREATE TABLE public.submissions (
  id           bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  problem_id   bigint,
  student_name text                     NOT NULL,
  is_anonymous boolean                  DEFAULT false NOT NULL,
  answer       text                     NOT NULL,
  is_correct   boolean,
  score        integer                  DEFAULT 0 NOT NULL,
  submitted_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.submissions
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.submissions
  ADD CONSTRAINT submissions_pkey PRIMARY KEY (id);

ALTER TABLE public.submissions
  ADD CONSTRAINT submissions_problem_id_fkey FOREIGN KEY (problem_id) REFERENCES public.problems(id) ON DELETE CASCADE;

GRANT INSERT, SELECT, UPDATE ON public.submissions TO anon;

GRANT MAINTAIN ON public.submissions TO authenticated;

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.submissions TO service_role;

CREATE POLICY "Public insert submissions" ON public.submissions
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Public read submissions" ON public.submissions
  FOR SELECT
  USING (true);

CREATE POLICY "Public update submissions" ON public.submissions
  FOR UPDATE
  USING (true);
